[build]
  base = "frontend/bookquotes-ui"
  command = "npm run build && cp dist/bookquotes-ui/browser/index.csr.html dist/bookquotes-ui/browser/index.html"
  publish = "dist/bookquotes-ui/browser"

[build.environment]
  NODE_VERSION = "24"
